export const PRODUCT_SERVICES = [
  { id: 'handset-wholesale', title: 'มือถือและแท็บเล็ต', titleEn: 'Smartphones & Tablets', eyebrow: 'HANDSET WHOLESALE', group: 'sell', description: 'สินค้าเครื่องศูนย์ไทยหลากหลายแบรนด์ เช็กรุ่นและราคาส่งกับทีม PK', descriptionEn: 'Official Thai-market devices across multiple brands. Check models and wholesale pricing with PK.' },
  { id: 'stock-on-demand', title: 'Stock on Demand', titleEn: 'Stock on Demand', eyebrow: 'MORE CHOICE. LESS STOCK.', group: 'sell', description: 'ต่อยอดตัวเลือกขายด้วยสต็อก PK โดยยืนยันสินค้า ราคา และรอบส่งก่อน', descriptionEn: 'Extend your sales options with PK stock, after confirming availability, price and dispatch.' },
  { id: 'accessories', title: 'อุปกรณ์เสริมและแกดเจ็ต', titleEn: 'Accessories & Gadgets', eyebrow: 'COMPLETE EVERY CONNECTION', group: 'sell', description: 'เคส หัวชาร์จ หูฟัง และ Link Up by AIS เติมความครบให้ทุกการใช้งาน', descriptionEn: 'Cases, chargers, audio and Link Up by AIS. Complete the customer’s device experience.' },
  { id: 'ais-sim', title: 'ซิมและแพ็กเกจ AIS', titleEn: 'AIS SIM & Packages', eyebrow: 'CONNECT MORE POSSIBILITIES', group: 'customer', description: 'เพิ่มทางเลือกการเชื่อมต่อให้ลูกค้า ตามสิทธิ์ร้าน พื้นที่ และเงื่อนไขผู้ให้บริการ', descriptionEn: 'Connectivity options for your customers, subject to shop eligibility, territory and carrier terms.' },
  { id: 'ais-rom', title: 'เติมเงินออนไลน์', titleEn: 'Online Top-Up', eyebrow: 'KEEP THE RELATIONSHIP GOING', group: 'customer', description: 'อีกจังหวะให้ลูกค้ากลับมาที่ร้าน สอบถามการเข้าร่วมและเงื่อนไขบริการกับทีม', descriptionEn: 'Another reason for customers to return. Discuss participation and service terms with the team.' },
  { id: 'finance', title: 'S Leasing Hub', titleEn: 'S Leasing Hub', eyebrow: 'ANOTHER WAY FORWARD', group: 'customer', description: 'PK Hub เป็น Hub รับสมัครตัวแทน S Leasing สอบถามพื้นที่และเกณฑ์การเข้าร่วม', descriptionEn: 'PK Hub recruits S Leasing agents. Check territory and participation requirements with our team.' },
  { id: 'partner-marketing', title: 'Partner Marketing', titleEn: 'Partner Marketing', eyebrow: 'FREE PARTNER MARKETING', group: 'customer', description: 'สื่อกลางและแคมเปญฟรีสำหรับพาร์ทเนอร์ ไม่มีขั้นต่ำยอดซื้อ', descriptionEn: 'Free campaign media for every PK Hub Partner, with no minimum purchase.' },
  { id: 'after-sales', title: 'ทีมดูแลหลังการขาย', titleEn: 'After-Sales Support', eyebrow: 'STAY WITH YOUR CUSTOMER', group: 'care', description: 'ให้ PK ช่วยประสานและติดตาม หรือเลือกติดต่อศูนย์แบรนด์โดยตรง', descriptionEn: 'PK helps coordinate and follow up, or you can contact a brand service centre directly.' },
  { id: 'repair', title: 'ดูแลและซ่อมอุปกรณ์', titleEn: 'Device Care & Repair', eyebrow: 'CARE BEYOND THE SALE', group: 'care', description: 'ปรึกษางานบริการ ประเมินขอบเขตและเงื่อนไขกับทีมก่อนรับงาน', descriptionEn: 'Discuss service needs and confirm scope and terms with the team before accepting a job.' },
] as const

export type ProductId = typeof PRODUCT_SERVICES[number]['id']
export type ServiceProductId = Exclude<ProductId, 'stock-on-demand' | 'partner-marketing'>
export const SERVICE_PRODUCT_IDS = PRODUCT_SERVICES.filter(p => p.id !== 'stock-on-demand' && p.id !== 'partner-marketing').map(p => p.id) as ServiceProductId[]
export const productPath = (language: 'th' | 'en', id: ProductId) => `/${language}/products/${id}`
export const isProductRoute = (path: string) => /^\/(th|en)\/products\/?$/.test(path) || PRODUCT_SERVICES.some(p => new RegExp(`^/(th|en)/products/${p.id}/?$`).test(path))
export const CAPABILITY_PRODUCT: Record<string, ProductId> = { supply: 'handset-wholesale', stock: 'stock-on-demand', accessories: 'accessories', sim: 'ais-sim', topup: 'ais-rom', finance: 'finance', marketing: 'partner-marketing', support: 'after-sales', repair: 'repair' }
