import { useState } from 'react'
import { useLocation } from 'react-router-dom'
import { AnimatePresence, m } from 'framer-motion'
import { ArrowLeft, ArrowRight, ArrowUpRight, Check, ChevronDown, MessageCircle } from 'lucide-react'
import Navbar from '@/components/Navbar'
import ProductVisual from '@/components/pkhub-v7/ProductVisual'
import { ProductServiceLinks, ServiceValueFlow } from '@/components/pkhub-v7/ProductStoryMotion'
import { PRODUCT_SERVICES, SERVICE_PRODUCT_IDS, type ServiceProductId } from '@/content/productServices'
import { useLanguage } from '@/i18n/LanguageContext'
import { useRevealMotion } from '@/lib/motion'
import { getProductMeta, usePageMeta } from '@/lib/seo'
import BrandsSection from '@/pages/home/BrandsSection'
import Footer from '@/pages/home/Footer'
import PartnerStartSection from '@/pages/home/PartnerStartSection'
import { CONTACT } from '@/pages/home/constants'
import NotFound from '@/pages/NotFound'
import '@/styles/product-services.css'

type Copy = {
  headline: [string, string]
  intro: string
  cta: string
  note: string
  benefitTitle: [string, string]
  benefitBody: string
  benefits: [string, string][]
  journeyTitle: string
  steps: [string, string, string][]
  questions: [string, string][]
  related: [ServiceProductId | 'stock-on-demand' | 'partner-marketing', ServiceProductId | 'stock-on-demand' | 'partner-marketing']
}

const SERVICE_QUESTIONS: Record<ServiceProductId, [string,string]> = {
  'handset-wholesale': ['ลูกค้าถามคนละรุ่น ร้านคุณมีทางเลือกแค่ไหน?', 'Different customers, different devices. How much choice can you offer?'],
  accessories: ['ถ้าซื้อเครื่องแล้ว ลูกค้ายังต้องไปหาอุปกรณ์ที่อื่น?', 'What if the customer still has to buy accessories somewhere else?'],
  'ais-sim': ['เครื่องใหม่พร้อมแล้ว ลูกค้าพร้อมใช้งานหรือยัง?', 'The new device is ready. Is your customer connected?'],
  'ais-rom': ['หลังขายเครื่อง อะไรทำให้ลูกค้ากลับมาหาคุณ?', 'After the device sale, what brings your customer back?'],
  finance: ['ถ้าลูกค้าชอบเครื่อง แต่ยังไม่พร้อมจ่ายเต็มจำนวน?', 'What if a customer wants the device but needs another payment option?'],
  'after-sales': ['ถ้าลูกค้ากลับมาพร้อมปัญหา ร้านจะช่วยเขาไปต่ออย่างไร?', 'When a customer returns with an issue, how can your shop help?'],
  repair: ['ถ้าเครื่องมีอาการ ลูกค้าจะเริ่มขอคำแนะนำจากใคร?', 'When a device has an issue, who can your customer talk to first?'],
}

const DEALER_OUTCOMES: Record<ServiceProductId,[string,string]> = {
  'handset-wholesale':['ร้านเลือกซื้อเข้าสต็อกได้ตรงกับกลุ่มลูกค้า','Build an assortment that fits your shop’s customers.'],
  accessories:['มีโอกาสต่อยอดยอดขายในบิลของร้าน','Create an opportunity to add to your shop’s sale.'],
  'ais-sim':['มีบริการให้ร้านเสนอต่อจากการขายเครื่อง ตามสิทธิ์ที่ได้รับ','Offer connectivity after the device sale, within your approved eligibility.'],
  'ais-rom':['มีอีกจังหวะให้ร้านพบและดูแลลูกค้าซ้ำ','Give your shop another touchpoint with returning customers.'],
  finance:['เพิ่มทางเลือกผ่อนที่ร้านเสนอได้ ตามเกณฑ์ S Leasing','Explore a payment option your shop can offer under S Leasing requirements.'],
  'after-sales':['รักษาความสัมพันธ์กับลูกค้าของร้านหลังขาย','Keep your shop’s customer relationship after the sale.'],
  repair:['มีช่องทางให้ร้านปรึกษางานบริการก่อนรับเครื่อง','Give your shop a service contact before accepting a device.'],
}

function ServiceContent({ id }: { id: ServiceProductId }) {
  const { isThai, language } = useLanguage()
  const { item, reduceMotion } = useRevealMotion()
  const [activeStep, setActiveStep] = useState(0)
  const service = PRODUCT_SERVICES.find(p => p.id === id)!
  usePageMeta(getProductMeta(id, language))

  const th: Record<ServiceProductId, Copy> = {
    'handset-wholesale': {
      headline: ['สินค้าที่ลูกค้าต้องการ', 'พาร์ทเนอร์ที่ร้านไว้ใจ'], intro: 'มือถือและแท็บเล็ตเครื่องศูนย์ไทยหลากหลายแบรนด์ ให้ร้านเลือกสินค้าที่ตรงกับลูกค้า ตั้งแต่รุ่นเริ่มต้นถึงเรือธง', cta: 'เช็กรุ่นและราคาส่ง', note: 'เครื่องศูนย์ไทยแท้ · ใบกำกับภาษีเต็มรูปแบบ',
      benefitTitle: ['เลือกได้หลากหลาย', 'เริ่มจากร้านของคุณ'], benefitBody: 'คุยกลุ่มลูกค้าและรุ่นที่ร้านต้องการกับทีม PK แล้วเลือกสินค้าที่เหมาะกับจังหวะการขายของร้าน',
      benefits: [['หลายแบรนด์ หลายระดับ', 'เลือกมือถือและแท็บเล็ตให้ตรงกับการใช้งานและงบของลูกค้า'], ['เช็กข้อมูลก่อนสั่ง', 'ยืนยันรุ่น สี ความจุ ราคาปัจจุบัน และรอบส่งกับทีม'], ['มีทีมช่วยต่อ', 'คุยเรื่องการสั่งซื้อ เอกสาร และการประสานหลังการขาย']], journeyTitle: 'จากรุ่นที่ต้องการ สู่การสั่งซื้อ',
      steps: [['บอกรุ่นที่ร้านต้องการ', 'เริ่มที่ความต้องการของร้าน', 'ส่งรุ่น สี ความจุ และจำนวนที่ต้องการให้ทีม ไม่ต้องเดาว่ารุ่นไหนพร้อมขายจากภาพบนเว็บไซต์'], ['ยืนยันข้อมูลกับทีม PK', 'ข้อมูลปัจจุบันก่อนตัดสินใจ', 'เช็กราคา สต็อก เงื่อนไขการชำระเงิน และรอบส่งก่อนยืนยันออเดอร์'], ['รับสินค้าและดูแลลูกค้า', 'ต่อโอกาสให้หน้าร้าน', 'รับสินค้าตามรูปแบบที่ตกลง พร้อมเอกสารการซื้อ และช่องทางประสานหลังการขาย']],
      questions: [['มีราคาส่งและสต็อกบนหน้านี้ไหม?', 'เช็กราคาปัจจุบันกับทีมทาง LINE หรือใช้ Dealer Portal ตามสิทธิ์ที่ได้รับอนุมัติ ภาพบนหน้านี้แสดงกลุ่มสินค้า ไม่ใช่การยืนยันสต็อกสด'], ['ถ้ารุ่นที่ลูกค้าถามไม่ได้อยู่ที่ร้านล่ะ?', 'สำรวจ Stock on Demand แล้วคุยทางเลือกกับทีม PK โดยยืนยันสินค้า ราคา และการรับสินค้าก่อนรับปากลูกค้า']], related: ['stock-on-demand', 'accessories'],
    },
    accessories: {
      headline: ['เครื่องใหม่เป็นจุดเริ่มต้น', 'เติมความครบในบิลเดียว'], intro: 'เคส หัวชาร์จ หูฟัง และแกดเจ็ตที่เข้ากับการใช้งาน เพิ่มทางเลือกให้ลูกค้า พร้อมโอกาสต่อยอดจากการขายเครื่อง', cta: 'คุยชุดอุปกรณ์สำหรับร้าน', note: 'อุปกรณ์เสริมหลากหลาย · รวม Link Up by AIS',
      benefitTitle: ['ไม่ได้จบแค่เครื่อง', 'เริ่มจากการใช้งานจริง'], benefitBody: 'เลือกสิ่งที่ลูกค้าต้องใช้ร่วมกับเครื่อง ให้คำแนะนำที่มีเหตุผล และช่วยให้ร้านเสนอสินค้าได้ครบขึ้น', benefits: [['เสนอขายคู่กับเครื่อง', 'เคสและอุปกรณ์ปกป้องที่ร้านเลือกให้ตรงกับรุ่นของลูกค้า'], ['จัดชุดพร้อมใช้', 'หัวชาร์จและอุปกรณ์ชาร์จที่ร้านนำไปเสนอให้ลูกค้าเลือกได้'], ['เติมตัวเลือกในบิล', 'หูฟังและแกดเจ็ตที่ร้านเสนอเพิ่มเติมตามการใช้งานของลูกค้า']], journeyTitle: 'จับคู่สินค้าให้ตรงความต้องการ',
      steps: [['เริ่มจากรุ่นและการใช้งาน', 'เลือกให้ตรง ไม่ใช่เพิ่มให้เยอะ', 'ดูรุ่นอุปกรณ์และสิ่งที่ลูกค้าต้องการใช้ร่วมกัน เช่น ปกป้องเครื่อง ชาร์จ หรือฟังเพลง'], ['เช็กตัวเลือกกับ PK', 'ชุดสินค้าที่ร้านนำไปเสนอได้', 'ยืนยันสินค้า ความเข้ากันได้ ราคา และเงื่อนไขก่อนจัดชุดให้ลูกค้า'], ['ต่อยอดในบิลเดียว', 'อธิบายประโยชน์ให้ลูกค้าเลือก', 'เสนอเฉพาะสิ่งที่ช่วยเติมความครบให้การใช้งาน โดยร้านเลือกชุดและราคาขายตามเงื่อนไขที่ตกลง']],
      questions: [['ต้องซื้อพร้อมมือถือเท่านั้นไหม?', 'คุยความต้องการและรูปแบบการสั่งซื้ออุปกรณ์เสริมกับทีมได้ โดยตรวจสอบรายการสินค้า ราคา และเงื่อนไขปัจจุบันก่อน'], ['มีตัวเลขกำไรต่อชิ้นไหม?', 'ขอราคาปัจจุบันของรายการที่สนใจจากทีม แล้วพิจารณาต้นทุนและราคาขายที่เหมาะกับร้าน']], related: ['handset-wholesale', 'partner-marketing'],
    },
    'ais-sim': {
      headline: ['เครื่องพร้อม', 'การเชื่อมต่อก็พร้อมต่อ'], intro: 'ซิมและแพ็กเกจ AIS ช่วยต่อบทสนทนาจากเครื่องใหม่ สู่บริการที่ตรงกับการใช้งานของลูกค้า', cta: 'สอบถามซิมและสิทธิ์ร้าน', note: 'สิทธิ์ร้าน พื้นที่ และเงื่อนไขเป็นไปตามผู้ให้บริการ',
      benefitTitle: ['อีกความต้องการ', 'ที่ร้านช่วยลูกค้าได้'], benefitBody: 'เริ่มจากรูปแบบใช้งานของลูกค้า แล้วเช็กตัวเลือกบริการและสิทธิ์ของร้านก่อนเสนอซิมหรือแพ็กเกจ', benefits: [['ซิมที่ตรงกับลูกค้า', 'สอบถามตัวเลือกซิมและบริการที่เหมาะกับการใช้งาน'], ['แพ็กเกจตามเงื่อนไข', 'เช็กสิทธิ์และรายละเอียดปัจจุบันก่อนเสนอให้ลูกค้า'], ['ต่อยอดความสัมพันธ์', 'เชื่อมการซื้อเครื่องกับบทสนทนาเรื่องบริการที่ลูกค้าต้องการ']], journeyTitle: 'เช็กสิทธิ์ก่อน เปิดโอกาสต่อ',
      steps: [['คุยพื้นที่และสิทธิ์ร้าน', 'เริ่มที่เงื่อนไขที่ใช้กับร้านคุณ', 'สอบถามเรื่องพื้นที่ รหัสร้าน การเข้าร่วม และบริการที่ร้านสามารถเสนอได้กับทีม'], ['เลือกบริการที่เหมาะ', 'ให้การใช้งานของลูกค้าเป็นตัวตั้ง', 'เช็กซิม แพ็กเกจ และเงื่อนไขของรายการที่สนใจ ไม่ใช้รายละเอียดจากภาพซิมเป็นข้อเสนอปัจจุบัน'], ['ยืนยันก่อนดำเนินการ', 'ชัดเจนทั้งร้านและลูกค้า', 'ตรวจสอบรายละเอียด เอกสารที่ต้องใช้ และขั้นตอนตามผู้ให้บริการก่อนทำรายการ']],
      questions: [['ร้านทุกพื้นที่ใช้สิทธิ์เหมือนกันไหม?', 'สิทธิ์บริการ AIS ขึ้นกับรหัสร้าน พื้นที่ และเงื่อนไขผู้ให้บริการ การเป็นพาร์ทเนอร์ PK ไม่ได้หมายถึงได้รับสิทธิ์ AIS ทุกบริการโดยอัตโนมัติ'], ['ภาพซิมเป็นโปรโมชั่นปัจจุบันหรือเปล่า?', 'ภาพใช้แสดงกลุ่มบริการเท่านั้น ให้ทีมยืนยันซิม แพ็กเกจ ราคา สิทธิ์ และระยะเวลาโปรโมชั่นก่อนเสนอขาย']], related: ['ais-rom', 'handset-wholesale'],
    },
    'ais-rom': {
      headline: ['เติมเงินเป็นอีกจังหวะ', 'ให้ลูกค้ากลับมาหาคุณ'], intro: 'สร้างจุดเชื่อมต่อกับลูกค้าอย่างต่อเนื่อง ผ่านบริการเติมเงินออนไลน์ที่ร้านตรวจสอบเงื่อนไขกับทีมก่อนเข้าร่วม', cta: 'คุยเรื่องบริการเติมเงิน', note: 'ตัวเลขแสดงยอดเติมเงินต่อรายการ ไม่ใช่ค่าตอบแทนร้าน',
      benefitTitle: ['ความสัมพันธ์', 'ไม่จบที่หนึ่งบิล'], benefitBody: 'เมื่อลูกค้ากลับมาใช้บริการ ร้านก็มีโอกาสดูแลต่อ และคุยเรื่องสินค้าและบริการที่ตรงกับความต้องการ', benefits: [['มีเหตุผลให้กลับมา', 'บริการต่อเนื่องเป็นอีกจังหวะพบลูกค้าที่ร้าน'], ['ตรวจสอบก่อนทำรายการ', 'เช็กผู้รับ ยอดเติมเงิน และรายละเอียดตามช่องทางบริการ'], ['คุยเงื่อนไขให้ชัด', 'สอบถามการเข้าร่วม การทำรายการ และเงื่อนไขค่าตอบแทนกับทีม']], journeyTitle: 'เริ่มบริการด้วยข้อมูลที่ชัดเจน',
      steps: [['สอบถามการเข้าร่วม', 'เลือกช่องทางที่เหมาะกับร้าน', 'ให้ทีมตรวจสอบขอบเขตบริการ สิทธิ์ และเงื่อนไขที่ใช้กับร้านก่อนเริ่มใช้งาน'], ['ยืนยันรายละเอียดรายการ', 'ยอดเงินและผู้รับต้องถูกต้อง', 'ตรวจสอบยอดเติมเงิน ข้อมูลผู้รับ และเงื่อนไขการทำรายการก่อนดำเนินการผ่านช่องทางบริการ'], ['ติดตามผลกับช่องทางบริการ', 'ดูแลลูกค้าต่ออย่างเข้าใจ', 'ใช้ช่องทางบริการที่ยืนยันในการติดตามผลหรือสอบถามปัญหา ไม่อ้างอิงสถานะจากภาพประกอบบนเว็บไซต์']],
      questions: [['1,000 THB คือกำไรหรือยอดเติมเงิน?', 'เป็นยอดเติมเงินต่อรายการที่ใช้ประกอบการอธิบาย ไม่ใช่รายได้ ค่าคอมมิชชัน หรือยอดรับประกันของร้าน'], ['ค่าตอบแทนและเงื่อนไขการเริ่มบริการเป็นอย่างไร?', 'ให้ทีมยืนยันอัตรา ฐานคำนวณ ข้อกำหนด การชำระเงิน และเงื่อนไขการทำรายการที่ใช้กับร้านก่อนเริ่มบริการ']], related: ['ais-sim', 'partner-marketing'],
    },
    finance: {
      headline: ['อีกทางเลือกผ่อน', 'อีกโอกาสให้หน้าร้าน'], intro: 'PK Hub เป็น Hub รับสมัครตัวแทน S Leasing ให้ร้านที่สนใจเพิ่มทางเลือกผ่อนชำระ เริ่มจากการคุยพื้นที่และเงื่อนไขกับทีม', cta: 'สนใจเป็นตัวแทน S Leasing', note: 'การเข้าร่วมและสินเชื่อพิจารณาตามเกณฑ์ผู้ให้บริการ',
      benefitTitle: ['ร้านของคุณ', 'เชื่อมกับ S Leasing ผ่าน PK'], benefitBody: 'ให้ทีมช่วยคุยขั้นตอนการเข้าร่วมและข้อมูลที่ต้องตรวจสอบ เพื่อให้ร้านเข้าใจขอบเขตบริการก่อนตัดสินใจ', benefits: [['PK เป็น Hub', 'รับสมัครตัวแทนและช่วยเชื่อมการพูดคุยกับผู้ให้บริการ'], ['เช็กพื้นที่และสิทธิ์', 'การเข้าร่วมขึ้นกับข้อกำหนดของ S Leasing'], ['เข้าใจเงื่อนไขก่อน', 'คุยเอกสาร ขอบเขตบริการ และข้อมูลที่ต้องยืนยันกับทีม']], journeyTitle: 'จากร้านที่สนใจ สู่การคุยเงื่อนไข',
      steps: [['คุยข้อมูลร้านกับทีม PK', 'เริ่มที่ความต้องการของร้าน', 'แจ้งพื้นที่และความสนใจในการเป็นตัวแทน เพื่อให้ทีมตรวจสอบช่องทางและเงื่อนไขการเข้าร่วม'], ['ตรวจสอบเกณฑ์ S Leasing', 'เงื่อนไขมาจากผู้ให้บริการ', 'สอบถามเอกสาร สิทธิ์ ขอบเขต และขั้นตอนที่ต้องใช้ หลีกเลี่ยงการรับปากผลอนุมัติให้ลูกค้า'], ['ตัดสินใจจากข้อมูลที่ยืนยัน', 'ชัดเจนก่อนเริ่มให้บริการ', 'ให้ทีมอธิบายเงื่อนไขที่ใช้กับร้านก่อนเข้าร่วม การเป็นพาร์ทเนอร์ PK ไม่ได้เปิดสิทธิ์สินเชื่อโดยอัตโนมัติ']],
      questions: [['PK Hub เป็นผู้อนุมัติสินเชื่อไหม?', 'PK Hub เป็น Hub รับสมัครตัวแทน S Leasing การพิจารณาและอนุมัติสินเชื่อเป็นไปตามเกณฑ์ของผู้ให้บริการ'], ['มีอัตราดอกเบี้ย ค่าธรรมเนียม หรือค่าตอบแทนบนหน้านี้ไหม?', 'ให้ทีมช่วยยืนยันอัตรา ค่าธรรมเนียม และค่าตอบแทนที่ใช้กับร้าน ตามข้อเสนอผู้ให้บริการก่อนตัดสินใจ']], related: ['handset-wholesale', 'stock-on-demand'],
    },
    'after-sales': {
      headline: ['ขายแล้ว ยังมีทีมช่วย', 'ดูแลลูกค้าต่อไปด้วยกัน'], intro: 'ร้านดูแลความสัมพันธ์กับลูกค้า ให้ PK ช่วยประสานช่องทางแบรนด์และติดตามข้อมูลหลังการขายตามเงื่อนไขสินค้า', cta: 'คุยเรื่องประสานหลังการขาย', note: 'ร้านเลือกติดต่อศูนย์แบรนด์โดยตรงได้เช่นกัน',
      benefitTitle: ['ลูกค้าคุยกับร้าน', 'ร้านมีทีมช่วยต่อ'], benefitBody: 'เริ่มจากข้อมูลสินค้าและอาการที่พบ แล้วเลือกติดต่อศูนย์บริการโดยตรง หรือให้ทีม PK ช่วยประสานและติดตาม', benefits: [['ตรวจข้อมูลก่อน', 'เตรียมรายละเอียดสินค้า อาการ และหลักฐานการซื้อ'], ['มีทางเลือกในการติดต่อ', 'ติดต่อแบรนด์โดยตรง หรือคุยให้ PK ช่วยประสาน'], ['สื่อสารกับลูกค้าต่อ', 'ติดตามข้อมูลผ่านช่องทางที่ตกลง ไม่คาดเดาผลการเคลม']], journeyTitle: 'ประสานอย่างชัดเจนในแต่ละจังหวะ',
      steps: [['แจ้งข้อมูลและอาการ', 'ให้ข้อมูลที่ช่วยตรวจสอบได้', 'คุยรุ่นสินค้า อาการ หลักฐานการซื้อ และข้อมูลที่ทีมร้องขอผ่านช่องทางที่เหมาะสม'], ['ตรวจเงื่อนไขแบรนด์', 'เลือกเส้นทางบริการที่เหมาะ', 'ให้ทีมช่วยตรวจสอบช่องทางและขอบเขตการประสาน หรือเลือกติดต่อศูนย์บริการแบรนด์โดยตรง'], ['ติดตามและแจ้งลูกค้า', 'ดูแลความสัมพันธ์หลังการขาย', 'นัดหมายและแจ้งความคืบหน้าตามข้อมูลที่ได้รับจากช่องทางบริการ ผลและระยะเวลาเป็นไปตามเงื่อนไขแบรนด์']],
      questions: [['จำเป็นต้องส่งผ่าน PK ทุกครั้งไหม?', 'ไม่จำเป็น ร้านเลือกติดต่อศูนย์บริการของแบรนด์โดยตรง หรือคุยให้ทีม PK ช่วยประสานตามขอบเขตที่ตกลงได้'], ['PK รับประกันผลการเคลมหรือระยะเวลาไหม?', 'ผลการตรวจสอบ การรับประกัน และระยะเวลาบริการเป็นไปตามผู้ผลิตหรือผู้ให้บริการ ให้ทีมยืนยันข้อมูลที่ใช้กับสินค้านั้นก่อนแจ้งลูกค้า']], related: ['repair', 'handset-wholesale'],
    },
    repair: {
      headline: ['ดูแลเครื่อง', 'ดูแลความสัมพันธ์ต่อ'], intro: 'อีกบทสนทนาเรื่องบริการที่ร้านช่วยลูกค้าได้ ปรึกษาอาการและความต้องการกับทีม PK เพื่อเช็กขอบเขตงานก่อนรับบริการ', cta: 'ปรึกษางานบริการกับทีม', note: 'ตรวจสอบรุ่น ขอบเขตงาน และเงื่อนไขก่อนรับเครื่อง',
      benefitTitle: ['เริ่มจากอาการ', 'ไม่เริ่มจากคำรับประกัน'], benefitBody: 'เข้าใจความต้องการของลูกค้า แล้วคุยเรื่องการตรวจประเมิน ค่าใช้จ่าย และเงื่อนไขให้ชัดเจนก่อนรับงาน', benefits: [['เล่าอาการให้ครบ', 'รุ่นสินค้า อาการ และสิ่งที่ลูกค้าต้องการให้ช่วย'], ['คุยขอบเขตก่อน', 'ตรวจสอบงานที่ให้บริการได้ รวมถึงอะไหล่และเงื่อนไข'], ['ดูแลข้อมูลหลังรับงาน', 'นัดหมายและติดตามผ่านช่องทางที่ยืนยันกับทีม']], journeyTitle: 'ปรึกษาก่อนรับงาน ให้ทุกฝ่ายเข้าใจ',
      steps: [['แจ้งรุ่นและอาการ', 'เริ่มที่สิ่งที่ลูกค้าพบ', 'ส่งรายละเอียดอาการและรุ่นอุปกรณ์ให้ทีมตรวจสอบขอบเขตบริการก่อนรับปากลูกค้า'], ['คุยการประเมินและเงื่อนไข', 'ข้อมูลที่ต้องชัดก่อนเริ่ม', 'ยืนยันค่าตรวจประเมิน ค่าใช้จ่าย อะไหล่ ระยะเวลา และเงื่อนไขที่ใช้กับงานนั้นก่อนตัดสินใจ'], ['ยืนยันรูปแบบรับงาน', 'ดูแลลูกค้าตามสิ่งที่ตกลง', 'คุยเรื่องการรับส่งเครื่อง ผู้ดูแล การติดตาม และงานหลังบริการ โดยไม่ใช้ภาพประกอบแทนผลวินิจฉัย']],
      questions: [['ซ่อมได้ทุกรุ่นและทุกอาการไหม?', 'งานบริการขึ้นกับรุ่น อาการ และความพร้อมของผู้ให้บริการ ให้ทีมยืนยันขอบเขตก่อนรับงาน'], ['มีราคาซ่อมหรือระยะเวลาตายตัวไหม?', 'ค่าใช้จ่าย ระยะเวลา อะไหล่ และเงื่อนไขงานต้องตรวจสอบกับทีมเป็นรายกรณี ก่อนร้านแจ้งหรือรับปากลูกค้า']], related: ['after-sales', 'accessories'],
    },
  }
  const en: Record<ServiceProductId, Copy> = {
    'handset-wholesale': { headline: ['The devices they want.', 'The partner you trust.'], intro: 'Official Thai-market smartphones and tablets across multiple brands. Match your customers, from entry-level to flagship.', cta: 'Check models & wholesale prices', note: 'Official Thai-market devices · Full tax invoices', benefitTitle: ['More choice.', 'Built around your shop.'], benefitBody: 'Tell PK about your customers and the models you need, then choose an assortment that suits your sales.', benefits: [['Multiple brands and tiers', 'Match smartphones and tablets to customer needs and budgets.'], ['Check before ordering', 'Confirm the model, colour, storage, current price and dispatch.'], ['A team to help', 'Discuss ordering, documents and after-sales coordination.']], journeyTitle: 'From the right model to your order', steps: [['Tell us what you need', 'Start with your shop’s needs', 'Share the model, colour, storage and quantity you need. Images on this site do not confirm live availability.'], ['Confirm with PK', 'Current information before deciding', 'Check price, stock, payment terms and dispatch before confirming your order.'], ['Receive and serve', 'Bring the opportunity to your shop', 'Receive stock under the agreed arrangement, with purchase documents and an after-sales contact.']], questions: [['Are live prices and stock listed here?', 'Check current prices with PK on LINE, or use the Dealer Portal under your approved access. Images illustrate the product range.'], ['What if a model is not on my shelf?', 'Explore Stock on Demand and discuss options with PK. Confirm stock, price and receiving before making a promise.']], related: ['stock-on-demand', 'accessories'] },
    accessories: { headline: ['A new device is a start.', 'Complete the experience.'], intro: 'Cases, chargers, audio and gadgets that fit the customer’s needs. Offer a more complete experience alongside the device.', cta: 'Discuss your accessory range', note: 'Accessories & gadgets · Including Link Up by AIS', benefitTitle: ['Beyond the handset.', 'Built for real use.'], benefitBody: 'Recommend what works with the customer’s device. Explain the purpose of each accessory so they can make a useful choice.', benefits: [['Offer alongside the device', 'Choose compatible cases and protection for your customer.'], ['Build a ready-to-use set', 'Give your shop charging options to recommend.'], ['Add choice to the basket', 'Offer audio and gadgets that suit your customer’s use.']], journeyTitle: 'Match the accessory to the need', steps: [['Start with device and use', 'Choose what helps', 'Consider the model and what the customer needs alongside it: protection, charging or audio.'], ['Check the options with PK', 'An assortment you can offer', 'Confirm compatibility, current products, prices and terms before proposing a set.'], ['Build a complete basket', 'Let the benefit guide the choice', 'Offer accessories that improve the experience. Choose the set and retail pricing under the agreed terms.']], questions: [['Must accessories be ordered with a phone?', 'Discuss your accessory needs and ordering options with PK, then confirm current products, prices and terms.'], ['Is a margin percentage shown for every item?', 'Ask for current prices on the items you want, then consider the costs and retail pricing that suit your shop.']], related: ['handset-wholesale', 'partner-marketing'] },
    'ais-sim': { headline: ['The device is ready.', 'Keep them connected.'], intro: 'AIS SIMs and packages extend the conversation from a new handset to connectivity that fits the customer’s needs.', cta: 'Ask about SIMs & shop eligibility', note: 'Subject to shop eligibility, territory and carrier terms', benefitTitle: ['Another need.', 'Another conversation.'], benefitBody: 'Start with how the customer uses their device, then check the options and your shop’s eligibility before offering a SIM or package.', benefits: [['A suitable SIM', 'Discuss SIM options and services for the customer’s use.'], ['Current package terms', 'Check eligibility and details before making an offer.'], ['A continuing relationship', 'Connect a handset purchase to the service the customer needs.']], journeyTitle: 'Check eligibility. Explore the options.', steps: [['Discuss shop and territory', 'Start with your shop’s requirements', 'Ask PK about territory, shop codes, participation and the services your shop may offer.'], ['Match the service', 'Let customer needs lead', 'Confirm SIMs, packages and current conditions. Product images are not current promotional offers.'], ['Confirm before proceeding', 'Clarity for shop and customer', 'Check the details, documents and carrier process before making a transaction.']], questions: [['Do all shops have the same AIS eligibility?', 'AIS services depend on shop codes, territory and carrier terms. PK partnership does not automatically grant every AIS service.'], ['Do SIM images show current promotions?', 'The images illustrate the service range. Confirm packages, pricing, eligibility and promotional dates with the team.']], related: ['ais-rom', 'handset-wholesale'] },
    'ais-rom': { headline: ['More than a top-up.', 'A reason to return.'], intro: 'Keep a regular connection with your customers through online top-up services, with participation and terms confirmed with PK first.', cta: 'Discuss online top-up services', note: 'The number shows a transaction amount, not shop commission', benefitTitle: ['One relationship.', 'More than one visit.'], benefitBody: 'A return visit is another chance to help a customer and discuss the products or services they need.', benefits: [['A reason to visit again', 'An ongoing service offers another shop touchpoint.'], ['Check before transacting', 'Verify the recipient, amount and service details.'], ['Understand the terms', 'Discuss participation, transactions and remuneration with the team.']], journeyTitle: 'Start with clear service information', steps: [['Discuss participation', 'A channel that suits your shop', 'Confirm service scope, eligibility and conditions before you start.'], ['Check the transaction', 'The amount and recipient must be right', 'Verify recipient details, amount and transaction terms before proceeding through the service channel.'], ['Follow up through the service', 'Continue looking after the customer', 'Use the confirmed service channel for status and enquiries. Website illustrations are not transaction results.']], questions: [['Is 1,000 THB income or a top-up amount?', 'It is a per-transaction top-up amount used to explain the service. It is not commission, income or guaranteed shop earnings.'], ['What are the rewards and participation terms?', 'Ask PK to confirm the rates, calculation basis, requirements, payments and transaction conditions applying to your shop before starting.']], related: ['ais-sim', 'partner-marketing'] },
    finance: { headline: ['Another way to buy.', 'Another shop opportunity.'], intro: 'PK Hub recruits agents for S Leasing. Shops interested in offering financing can start by discussing territory and participation with our team.', cta: 'Ask about becoming an S Leasing agent', note: 'Participation and credit decisions follow provider requirements', benefitTitle: ['Your shop.', 'Connected through PK.'], benefitBody: 'Discuss joining and the information to check so you understand the service scope before deciding.', benefits: [['PK is the Hub', 'Agent recruitment and a connection to the provider.'], ['Check territory and access', 'Participation follows S Leasing requirements.'], ['Understand the conditions', 'Confirm documents, scope and service details with PK.']], journeyTitle: 'From interest to understanding the terms', steps: [['Speak with PK', 'Start with your shop’s needs', 'Tell us your territory and interest in becoming an agent so the team can check participation options.'], ['Review S Leasing requirements', 'Provider-owned terms', 'Ask about documents, eligibility, scope and process. Do not promise customers an approval outcome.'], ['Decide on confirmed information', 'Clarity before offering the service', 'Understand the terms applying to your shop. PK partnership does not automatically grant financing access.']], questions: [['Does PK Hub approve customer credit?', 'PK Hub is an S Leasing agent recruitment Hub. Credit assessment and approval follow the provider’s requirements.'], ['Are rates, fees or agent rewards listed here?', 'Ask PK to confirm rates, fees and agent remuneration under the provider’s current offer before deciding.']], related: ['handset-wholesale', 'stock-on-demand'] },
    'after-sales': { headline: ['After the sale.', 'Still by your side.'], intro: 'Keep the customer relationship with your shop. PK helps coordinate brand service channels and follow up under the device’s terms.', cta: 'Discuss after-sales coordination', note: 'You can also contact a brand service centre directly', benefitTitle: ['Your customer.', 'A team behind you.'], benefitBody: 'Start with the device and issue. Contact the brand directly or discuss coordination and follow-up with PK.', benefits: [['Check the information', 'Prepare the device details, issue and purchase documents.'], ['Choose your contact route', 'Reach the brand directly or ask PK to help coordinate.'], ['Keep the customer informed', 'Follow up through the agreed channel without guessing outcomes.']], journeyTitle: 'Clear coordination at each stage', steps: [['Share details and the issue', 'Information that helps the check', 'Discuss the model, symptoms, purchase documents and information requested by the team through the appropriate channel.'], ['Check brand conditions', 'Choose the service route', 'Ask PK to check coordination scope and contacts, or reach the brand’s service centre directly.'], ['Follow up and communicate', 'Care after the sale', 'Arrange next steps using information from the service channel. Outcomes and timelines follow the brand’s terms.']], questions: [['Must every device go through PK?', 'No. Contact the brand’s service centre directly or discuss PK coordination under the agreed scope.'], ['Does PK guarantee claim outcomes or times?', 'Assessment, warranty coverage and service timelines belong to the manufacturer or provider. Confirm the applicable information before advising customers.']], related: ['repair', 'handset-wholesale'] },
    repair: { headline: ['Care for the device.', 'Keep the relationship.'], intro: 'Another service conversation your shop can support. Discuss the issue and needs with PK to check service scope before accepting a device.', cta: 'Discuss a service requirement', note: 'Confirm model, scope and terms before taking a device', benefitTitle: ['Start with the issue.', 'Confirm what is possible.'], benefitBody: 'Understand the customer’s needs, then clarify assessment, costs and conditions before accepting the work.', benefits: [['Describe the issue', 'Share the model, symptoms and help the customer needs.'], ['Confirm the scope', 'Check available work, parts and service conditions.'], ['Stay informed', 'Arrange receiving and follow-up through the agreed channel.']], journeyTitle: 'Discuss first. Agree before proceeding.', steps: [['Tell us model and symptoms', 'Start with what the customer sees', 'Share details so PK can check service scope before you make a commitment.'], ['Discuss assessment and terms', 'Clarity before starting', 'Confirm assessment charges, costs, parts, timing and conditions for the specific job.'], ['Agree the service arrangement', 'Deliver on what is agreed', 'Discuss receiving, custody, follow-up and after-service support. The illustration is not a diagnosis.']], questions: [['Can every model and issue be repaired?', 'Service depends on the model, issue and provider readiness. Ask the team to confirm the scope before accepting the work.'], ['Are costs or turnaround fixed?', 'Costs, parts, timing and conditions need case-specific confirmation before your shop makes a commitment.']], related: ['after-sales', 'accessories'] },
  }
  const content = isThai ? th[id] : en[id]
  const selected = content.steps[activeStep]

  return <div id="pk-home-v7" className="is-service-product bg-white">
    <a href="#main-content" className="pk-skip-link">{isThai ? 'ข้ามไปเนื้อหา' : 'Skip to content'}</a>
    <div id="top" className="v4-page">
      <Navbar />
      <div className="ps-backbar"><a className="v4-text-action cursor-interaction" href={`/${language}/products`}><ArrowLeft size={15} aria-hidden="true" />{isThai ? 'สินค้าและบริการ' : 'Products & services'}</a><span>{isThai ? service.title : service.titleEn}</span></div>
      <main id="main-content" tabIndex={-1}>
        <section className="ps-hero" aria-labelledby="ps-title">
          <m.div className="ps-hero-copy" variants={item} initial="hidden" animate="show"><p className="v4-eyebrow">{service.eyebrow}<span className="pstory-audience-inline">{isThai ? 'สำหรับร้านพาร์ทเนอร์' : 'For retail partners'}</span></p><h1 id="ps-title">{content.headline[0]}<br /><span>{content.headline[1]}</span></h1><p className="ps-lead">{content.intro}</p><div className="ps-actions"><a className="v4-primary cursor-interaction" href={CONTACT.LINE_URL} target="_blank" rel="noreferrer"><MessageCircle size={16} aria-hidden="true" />{content.cta}</a></div><p className="ps-offer-note"><Check size={15} aria-hidden="true" />{content.note}</p></m.div>
          <m.div variants={item} initial="hidden" animate="show"><ProductVisual id={id} /></m.div>
        </section>
        {id === 'handset-wholesale' && <BrandsSection />}
        <section className="ps-benefits" aria-labelledby="ps-benefit-title"><m.div className="ps-section-copy" variants={item} initial="hidden" whileInView="show" viewport={{ once: true, amount: 0.25 }}><p className="v4-eyebrow">THINK BEYOND THE FIRST SALE</p><h2 id="ps-benefit-title" className="pstory-question">{SERVICE_QUESTIONS[id][isThai ? 0 : 1]}</h2><p>{content.benefitBody}</p><p className="pstory-dealer-outcome"><strong>{DEALER_OUTCOMES[id][isThai ? 0 : 1]}</strong></p><a className="v4-text-action cursor-interaction" href={CONTACT.LINE_URL} target="_blank" rel="noreferrer">{content.cta}<ArrowUpRight size={15} aria-hidden="true" /></a></m.div><ServiceValueFlow id={id} benefits={content.benefits} /></section>
        <section className="ps-journey" aria-labelledby="ps-journey-title"><div><p className="v4-eyebrow">THE NEXT STEP, MADE CLEAR</p><h2 id="ps-journey-title">{content.journeyTitle}</h2><div className="ps-journey-steps" role="group" aria-label={isThai ? 'สำรวจขั้นตอนบริการ' : 'Explore the service journey'}>{content.steps.map(([title], i) => <button key={title} type="button" aria-pressed={activeStep === i} onClick={() => setActiveStep(i)}><span>0{i + 1}</span><strong>{title}</strong><ArrowRight size={16} aria-hidden="true" /></button>)}</div></div><div className="ps-journey-detail-wrap"><AnimatePresence mode="wait" initial={false}><m.div key={activeStep} className="ps-journey-detail" initial={{opacity:1,y:reduceMotion?0:8}} animate={{opacity:1,y:0}} exit={{opacity:reduceMotion?1:0.4}} transition={{duration:reduceMotion?0:0.18}}><span className="ps-large-step" aria-hidden="true">0{activeStep + 1}</span><h3>{selected[1]}</h3><p>{selected[2]}</p><a className="v4-text-action cursor-interaction" href={CONTACT.LINE_URL} target="_blank" rel="noreferrer">{content.cta}<ArrowUpRight size={15} aria-hidden="true" /></a></m.div></AnimatePresence><span className="v6-sr" role="status">{selected[1]}</span></div></section>
        <section className="ps-questions" aria-labelledby="ps-questions-title"><h2 id="ps-questions-title">{isThai ? 'ก่อนเริ่มกับร้านคุณ' : 'Before you get started'}</h2><div>{content.questions.map(([q, a]) => <details key={q}><summary>{q}<ChevronDown size={18} aria-hidden="true" /></summary><p>{a}</p></details>)}</div></section>
        <section className="ps-related" aria-label={isThai ? 'สำรวจบริการที่เชื่อมกัน' : 'Explore connected services'}><p className="v4-eyebrow">MORE POSSIBILITIES, ONE PARTNER</p><ProductServiceLinks ids={content.related} /></section>
        <PartnerStartSection />
      </main>
      <Footer />
    </div>
  </div>
}

export default function ServiceProductPage() {
  const { pathname } = useLocation()
  const id = pathname.replace(/\/$/, '').split('/').pop() as ServiceProductId
  if (!SERVICE_PRODUCT_IDS.includes(id)) return <NotFound />
  return <ServiceContent key={id} id={id} />
}
